# Generated by Django 4.1 on 2023-06-10 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatterbox_app', '0005_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
