# Generated by Django 4.1 on 2023-06-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatterbox_app', '0008_remove_note_date_note_created_at_note_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='smtp_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='smtp_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
