# Generated by Django 4.1 on 2023-06-12 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatterbox_app', '0009_profile_smtp_email_profile_smtp_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='encryption_key',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='smtp_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
