# Generated by Django 4.1 on 2023-06-12 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatterbox_app', '0010_profile_encryption_key_alter_profile_smtp_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='encryption_key',
        ),
    ]
